version: "3.4"

services:
  app:
    image: chat_app:v1
    volumes:
      - ./:/app
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}"
    restart: unless-stopped
    depends_on:
      - db

  db:
    build:
      context: .
      dockerfile: Dockerfile.mongo
    volumes:
      - .docker/database:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=username
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=mongo
      - MONGO_REPLICA_HOST=localhost
      - MONGO_REPLICA_PORT=27017
    ports:
      - "27017:27017"
    restart: unless-stopped
