version: "3.4"

services:
  app:
    image: chat_app:v1
    volumes:
      - ./:/app
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - PORT=${PORT}
    ports:
      - "${PORT}:${PORT}"
    restart: unless-stopped
    depends_on:
      - db

  db:
    image: mongo:4.4
    volumes:
      - .docker/database:/data/db
    restart: unless-stopped
