version: "3.4"

services:
  # app:
  #   image: chat_app:v1
  #   volumes:
  #     - ./:/app
  #   env_file:
  #     - .env
  #   ports:
  #     - "${PORT}:${PORT}"
  #   restart: unless-stopped

  redis:
    container_name: chat_app_redis
    image: redis:latest
    ports:
      - 6379:6379
