#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo '🏗️👷 testing and buidling before commit'

yarn lint --fix ||
(
    echo 'ESLint Check Failed. Make the required changes listed above, add changes and try to commit again.'
    false;
)

echo 'I am committing this now.'
